### ISSUE TITLE
Infografía SDLC

### ISSUE THREAD

**Issue by Jaczibeth** [SistemasTecTlaxiaco/actividad-1-infografia-Jaczibeth#1]
[Infografía SDLC Jaczibeth (1).pdf](https://github.com/user-attachments/files/16854624/Infografia.SDLC.Jaczibeth.1.pdf)

**Comment by edgarmauricio123** [comment]
20% No se encontró ningún error y cumple los requerimientos de la rubrica

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
